
using System.Runtime.Serialization;

namespace Model.Json.CbsRest.Responses
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    // Type created for JSON at <<root>>
    [Newtonsoft.Json.JsonObjectAttribute(MemberSerialization = Newtonsoft.Json.MemberSerialization.OptIn)]
    public partial class LoginResponse
    {

        [Newtonsoft.Json.JsonPropertyAttribute()]
        public LoginResponseItems[] items;
    }

    // Type created for JSON at <<root>> --> items
    [Newtonsoft.Json.JsonObjectAttribute(MemberSerialization = Newtonsoft.Json.MemberSerialization.OptIn)]
    public partial class LoginResponseItems
    {

        [Newtonsoft.Json.JsonPropertyAttribute()]
        public string username;
    }

}